### ISSUE TITLE
Failures when running `clue pip install`

### ISSUE THREAD

**Issue by jcollado** [dankilman/clue#5]
I'm setting the development environment from scratch, so I've installed `clue`, run `clue env` and `clue apply` as in the documentation. Then I execute in the `cloudify` virtual environment `clue pip install` and I get failures because some of the python packages cannot be found with the expected version (`4.0a5`).

Looking at the first failure, what I see is that `cloudify-rest-service==4.0a5` depends on `cloudify-dsl-parser==4.0a5`, but that `cloudify-dsl-parser` version is not found:

``` bash
 cloudify-rest-service              | No matching distribution found for cloudify-dsl-parser==4.0a5 (from cloudify-rest-service==4.0a5)
```

After reviewing the `inputs.yaml` file that was automatically generated by `clue`, I see that `cloudify-dsl-parser` is indeed marked as a dependency of `cloudify-rest-service`:

``` yaml
  cloudify-manager:
    properties:
      project_dir: true
      resources:
      - resources
    python:
    - dependencies:
      - cloudify-dsl-parser
      - flask-securest
      name: cloudify-rest-service
      path: rest-service
```

and that `cloudify-rest-service` is a repository managed by `clue`:

``` yaml
  cloudify-dsl-parser:
    type: core
```

Hence, my understanding is that the `pip install -e` command should have been executed for `cloudify-dsl-parser` before the one for `cloudify-rest-service` and the failure shouldn't have happened because the right version of `cloudify-dsl-parser` would have been available at the time the `cloudify-rest-service` installation happened.

Is this correct or am I missing something?
